### ISSUE TITLE
ZFS disk encryption initalization fails in HardenedBSD 10-STABLE

### ISSUE THREAD

**Issue by Scarletts** [HardenedBSD/hardenedBSD-stable#1]
Previously reported to https://github.com/HardenedBSD/hardenedbsd, but actually doesn't seem to apply to -CURRENT.

ZFS disk encryption initialization in the installer never finishes. This has been reproduced on a VirtualBox VM with 2048/4096MB base memory and a 32gb disk, using Windows 7 as a host, and the most recent build with SHA256 checksum `4be32b363e54e21c2ebb0c8c675c6ecf92f7ad23bdbd90f1491d3fbd5c921e64`

In FreeBSD 10-STABLE initialization finishes in several seconds, as expected.

Interestingly there is some difference in the text printed during this process.

HardenedBSD:

~~~
GEOM_ELI: Device ada0p4.eli created.
GEOM_ELI: Encryption: AES-XTS 256
GEOM_ELI: Crypto: hardware
~~~

FreeBSD:

~~~
cryptosoft0: <software crypto> on motherboard
GEOM_ELI: Device ada0p4.eli created.
GEOM_ELI: Encryption: AES-XTS 256
GEOM_ELI: Crypto: software
~~~

**Comment by opntr** [comment]
Possible fix is in ElectroBSD: https://www.fabiankeil.de/sourcecode/electrobsd/ZFS-Optionally-let-spa_sync-wait-for-writable-vdev.diff

**Comment by opntr** [comment]
More info about the issue: https://github.com/HardenedBSD/hardenedBSD/issues/168 and the fix in FreeBSD's phabricator: https://reviews.freebsd.org/D8160 and in HardenedBSD: https://github.com/HardenedBSD/hardenedBSD-stable/releases/tag/HardenedBSD-10-STABLE-v46.14 https://github.com/HardenedBSD/hardenedBSD-stable/commit/f3eddd4e73c64e4b2b7b2ca5b968e6d742f3669a
