### ISSUE TITLE
Issue upgrading with hbsd-update

### ISSUE THREAD

**Issue by jmfgdev** [HardenedBSD/hardenedBSD-stable#11]
According to the man page on hbsd-update all I should need to do is run
`hbsd-update`

but when I do, I get
`[*] Could not get the version number`

I reinstalled with slightly different settings to see if that would fix it, and it didn't.

I appologize if this is pure user error, but after reading thru the man page and seeing how the example is the command I am trying to run and recieving an error, I figured this was a problem.

**Comment by opntr** [comment]
@lattera ?

**Comment by lattera** [comment]
I haven't been able to reproduce. But, what I should do is make the error reporting more developer friendly.

**Comment by opntr** [comment]
@jmfgdev : is there any update regarding to this bug?

We need more info (the output of the following commands):
* uname -a 
* sysctl hardening.

**Comment by jmfgdev** [comment]
A lot has happened since I had access to this VM, I might not anymore, but I'll gladly give hardenedbsd another shot and tell you all if I experience the same bug

**Comment by opntr** [comment]
I'll fix this bug here, please reopen them if still exists in https://github.com/hardenedbsd/hardenedbsd repo.
