### ISSUE TITLE
Segfault on shutdown/reboot

### ISSUE THREAD

**Issue by engblom** [HardenedBSD/hardenedBSD-stable#5]
Version 11.0

When shutting down the computer, right after the syncing of the remaining nodes, the system throws a segfault before finally shutting down/rebooting.

The system was installed with "Auto (ZFS)" and "MBR (BIOS)" options set. The rest was unouched.

**Comment by lattera** [comment]
I can take a look at this soon.

**Comment by opntr** [comment]
It is a panic or a LOR?

**Comment by lattera** [comment]
I'm going to guess LOR, but I'll double-check to be sure.

**Comment by lattera** [comment]
Can you provide a picture of the system during shutdown/reboot? I'd like to see the message on the console.

Additionally, what architecture (amd64, i386, etc.)?

**Comment by engblom** [comment]
For some reason I could not upload the picture here, so I dumped it here instead: http://picpaste.com/segfault.jpg

It is running on AMD64. FreeBSD does not have the same behavior on the same computer.

**Comment by lattera** [comment]
This would be a Lock Order Reversal (LOR). You don't see it on FreeBSD because the debugging options are turned off, so no warning messages get outputted to the console. This is safe to ignore. Closing issue since this LOR comes from upstream FreeBSD.
