### ISSUE TITLE
Netmap and Bhyve cause a kernel panic when used together on hardenedBSD-stable.

### ISSUE THREAD

**Issue by net-error** [HardenedBSD/hardenedBSD-stable#7]
Bug:

Netmap and Bhyve cause a kernel panic when used together on hardenedBSD-stable LATT-SEC.
Netmap and Bhyve do not cause a kernel panic when used together on FreeBSD11-stable GENERIC.

example: boot-pfsense.sh

        # load a guest
        bhyveload \
                -m ${mem} \
                -d ${disk} \
                -S \
                ${name}

        # run it
        bhyve -c ${cpu} -m ${mem} -A -H -P -S \
                -s 0:0,hostbridge \
                -s 1:0,lpc \
                -s 2:0,virtio-net,vale0:1 \
                -s 3:0,virtio-net,vale1:1 \
                -s 4:0,virtio-blk,${disk} \
                -s 5:0,virtio-rnd \
                -l com1,stdio \
                ${name}

result:

![img_20170220_203237](https://cloud.githubusercontent.com/assets/791003/23189832/b0ca111c-f849-11e6-80b6-d4569e42dc75.jpg)

**Comment by lattera** [comment]
Can you try the HARDENEDBSD kernel instead of LATT-SEC?

**Comment by net-error** [comment]
I thought LATT-SEC only disables debug options. But ok, will do....

**Comment by lattera** [comment]
It also adds VIMAGE, an experimental virtualized network stack.

**Comment by lattera** [comment]
I found the reason why you're seeing the issue: the HARDENEDBSD kernel, from which the LATT-SEC kernel inherits, enables the INVARIANTS flag. You're hitting an extra mutex locking check that's failing. The check should fail in FreeBSD as well, but won't cause a kernel panic due to INVARIANTS being disabled in FreeBSD 11-STABLE's GENERIC kernel. If you disable INVARIANTS and INVARIANT_SUPPORT (you'll also need to set the PAX_INSECURE_MODE kernel option), then your kernel won't panic.

**Comment by net-error** [comment]
Thank you for helping me out lattera. 

Can you explain PAX_INSECURE_MODE please.

Do I have less security if I have that set ?

**Comment by lattera** [comment]
PAX_INSECURE_MODE simply allows you to disable INVARIANTS. The INVARIANTS kernel option is a great kernel option to have enabled, since it adds a lot of sanity checks into the kernel. The PAX_INSECURE_MODE option simply says "I know what I'm doing."

**Comment by lattera** [comment]
I forgot to answer your last question: "Do I have less security if I have that set?" The answer is no, though you do lose some additional sanity checks within the kernel. INVARIANTS is technically a debugging option, meant for developers. No fundamental security will be lost by disabling INVARIANTS and enabling PAX_INSECURE_MODE.

**Comment by net-error** [comment]
Thank you lattera closing this bug.

If you could, when you have time, write a blog post on how to debug kernel panics using lldb or gdb.
I hate asking questions that a simple step though the code would fix.

Thanks again.
